name: ping_pong_bot
description: A sample Mineral bot that responds with "Pong!" when it receives "Ping!".
version: 1.0.0
publish_to: 'none'

environment:
  sdk: '>=3.3.0 <4.0.0'

# Add regular dependencies here.
dependencies:
  mineral:
    path: ../../core
  mineral_cache:
    path: ../../cache
  path: ^1.9.0
  yaml: ^3.1.2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0